apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  cluster-local-gateway: {}
  controller-custom-certs:
    name: ''
    type: ''
  deployments:
    - annotations:
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/rewriteAppHTTPProbers: 'true'
      name: activator
    - annotations:
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/rewriteAppHTTPProbers: 'true'
      name: autoscaler
  ingress:
    contour:
      enabled: false
    istio:
      enabled: true
    kourier:
      enabled: false
  knative-ingress-gateway: {}
  registry: {}
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  registry: {}
---
piVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  broker:
    defaultConfig:
      authSecretName: ''
      bootstrapServers: REPLACE_WITH_COMMA_SEPARATED_KAFKA_BOOTSTRAP_SERVERS
      numPartitions: 10
      replicationFactor: 3
    enabled: true
  channel:
    authSecretName: ''
    authSecretNamespace: ''
    bootstrapServers: REPLACE_WITH_COMMA_SEPARATED_KAFKA_BOOTSTRAP_SERVERS
    enabled: true
  high-availability:
    replicas: 1
  sink:
    enabled: true
  source:
    enabled: true
