apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cluster-admin-app-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: mesh-external
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: app-1
  labels:
    app: web-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http-web
  selector:
    app: web-server
