apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: amq_broker 
    repoURL: https://github.com/KameloTT/openshift.git
    targetRevision: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
