apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-app-of-apps
  namespace: developer-argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: developer-argocd
  source:
    path: team_apps/projects/
    repoURL: https://github.com/KameloTT/openshift.git
    targetRevision: argocd
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: false
