apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rosa-local-cluster-infra
  namespace: cluster-level-argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: rosa-local-cluster-infra project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
